### ISSUE TITLE
Not working if sources are not in a subdirectory

### ISSUE THREAD

**Issue by jdeniau** [g1a/composer-test-scenarios#4]
I added `composer-test-scenarios` on a package to test 3 different versions of Symfony on a folder with sources are on the root package. ie. :

```
root/
  composer.json
  SomeDir/
    SomeFile.php
  Tests/
```

I tried with  composer.json autoloading like this
```
"autoload": {
  "psr-4": {
    "Foo\\Bar\\": ""
  }
}
```

and 

```
"autoload": {
  "psr-4": {
    "Foo\\Bar\\": "/"
  }
}
```

As I moved everything in a `src` folder, I then got a symlink in scenario/symfony2/src and everything went right.

A possible solution here might be to make a symlink everytime like this:
`scenario/scenario-name/root → ../../` and update the composer.json autoload to add `root/` 

Or at least document it / warn if the autoloading contains "/" or ""

**Comment by greg-1-anderson** [comment]
Yeah right now this project wants you to put everything in `src` and `tests`. It's an aspirational goal to parse your composer.json file and make symlinks to whichever directory or directories you have defined in your autoload file.

As you point out, making a symlink to the root of the project would be a bit more tricky. Your proposed solution would probably work, though.

**Comment by greg-1-anderson** [comment]
Try again with version ^3.  The latest version of composer-test-scenarios does not rely on symlinks for autoloading. I haven't tested placing sources at the root of the project, but in general it should be easier now to get different layout schemas to work.

**Comment by greg-1-anderson** [comment]
This probably works now. Open a new issue if similar problems are encountered.
